services:

  mongodb:
    image: mongo:8
    container_name: restauranty-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - restauranty-network

  auth:
    build:
      context: ./backend/auth
    container_name: restauranty-auth
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - restauranty-network

  discounts:
    build:
      context: ./backend/discounts
    container_name: restauranty-discounts
    restart: unless-stopped
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    networks:
      - restauranty-network

  items:
    build:
      context: ./backend/items
    container_name: restauranty-items
    restart: unless-stopped
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    networks:
      - restauranty-network

  client:
    build:
      context: ./client
    container_name: restauranty-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - discounts
      - items
    networks:
      - restauranty-network

volumes:
  mongodb_data:

networks:
  restauranty-network:
    driver: bridge