apiVersion: apps/v1
kind: Deployment
metadata:
  name: restauranty-assistant
  namespace: restauranty

spec:
  replicas: 1

  selector:
    matchLabels:
      app: restauranty-assistant

  template:
    metadata:
      labels:
        app: restauranty-assistant

    spec:
      serviceAccountName: restauranty-assistant

      containers:
        - name: assistant
          image: acrrestaurantytatiana.azurecr.io/restauranty-assistant:latest

          ports:
            - containerPort: 8000

          env:
            - name: OLLAMA_URL
              value: "http://ollama:11434"

            - name: OLLAMA_MODEL
              value: "llama3.2:1b"
                
            - name: LOKI_URL
              value: "http://loki-gateway.monitoring.svc.cluster.local"

            - name: PROMETHEUS_URL
              value: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: assistant
  namespace: restauranty

spec:
  selector:
    app: restauranty-assistant

  ports:
    - port: 8000
      targetPort: 8000

  type: ClusterIP