apiVersion: apps/v1
kind: Deployment
metadata:
  name: restauranty-client
  namespace: restauranty

spec:
  replicas: 2

  selector:
    matchLabels:
      app: restauranty-client

  template:
    metadata:
      labels:
        app: restauranty-client

    spec:
      containers:
        - name: client
          image: acrrestaurantytatiana.azurecr.io/restauranty-client:v7

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: restauranty

spec:
  selector:
    app: restauranty-client

  ports:
    - port: 80
      targetPort: 80

  type: ClusterIP