apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: restauranty-auth-hpa
  namespace: restauranty
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restauranty-auth

  minReplicas: 2
  maxReplicas: 6

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: restauranty-items-hpa
  namespace: restauranty
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restauranty-items

  minReplicas: 2
  maxReplicas: 6

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: restauranty-discounts-hpa
  namespace: restauranty
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restauranty-discounts

  minReplicas: 2
  maxReplicas: 6

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60