apiVersion: apps/v1
kind: Deployment
metadata:
  name: restauranty-items
  namespace: restauranty

spec:
  replicas: 2

  selector:
    matchLabels:
      app: restauranty-items

  template:
    metadata:
      labels:
        app: restauranty-items

    spec:
      containers:
        - name: items

          # CI/CD replaces this with the current Git SHA before deployment
          image: acrrestaurantytatiana.azurecr.io/restauranty-items:latest

          ports:
            - containerPort: 3003

          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/Restauranty"

            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret-kv
                  key: CLOUD_NAME

            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret-kv
                  key: CLOUD_API_KEY

            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret-kv
                  key: CLOUD_API_SECRET

          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "restauranty-keyvault"

---
apiVersion: v1
kind: Service
metadata:
  name: items
  namespace: restauranty
  labels:
    app: restauranty-items

spec:
  selector:
    app: restauranty-items

  ports:
    - name: metrics
      port: 3003
      targetPort: 3003

  type: ClusterIP