apiVersion: apps/v1
kind: Deployment
metadata:
  name: restauranty-items
  namespace: restauranty

spec:
  replicas: 2

  selector:
    matchLabels:
      app: restauranty-items

  template:
    metadata:
      labels:
        app: restauranty-items

    spec:
      containers:
        - name: items
          image: acrrestaurantytatiana.azurecr.io/restauranty-items:v1

          ports:
            - containerPort: 3003

          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/Restauranty"

            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUD_NAME

            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUD_API_KEY

            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUD_API_SECRET

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: items
  namespace: restauranty

spec:
  selector:
    app: restauranty-items

  ports:
    - port: 3003
      targetPort: 3003

  type: ClusterIP