apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: restauranty-keyvault
  namespace: restauranty

spec:
  provider: azure

  secretObjects:
    - secretName: auth-secret-kv
      type: Opaque
      data:
        - objectName: restauranty-jwt-secret
          key: SECRET

    - secretName: cloudinary-secret-kv
      type: Opaque
      data:
        - objectName: cloudinary-name
          key: CLOUD_NAME

        - objectName: cloudinary-api-key
          key: CLOUD_API_KEY

        - objectName: cloudinary-api-secret
          key: CLOUD_API_SECRET

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    userAssignedIdentityID: "bbb4a786-b9c9-4c6f-bdc8-eaee5f63cad3"

    keyvaultName: "kv-restauranty-tatiana"
    tenantId: "84f58ce9-43c8-4932-b908-591a8a3007d3"

    objects: |
      array:
        - |
          objectName: restauranty-jwt-secret
          objectType: secret
        - |
          objectName: cloudinary-name
          objectType: secret
        - |
          objectName: cloudinary-api-key
          objectType: secret
        - |
          objectName: cloudinary-api-secret
          objectType: secret